JobBoard.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;
using PagedList;

namespace JobBoard.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Filters
        public ActionResult OpenPositionFilter()
        {
            
            var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);
            return View(openPositions.ToList());
        }

        



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI.MVC/Controllers/UserAdminController.cs
using JobBoard.UI.MVC.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;

namespace JobBoard.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

JobBoard.UI.MVC/Controllers/UserDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;
using Microsoft.AspNet.Identity;

namespace JobBoard.UI.MVC.Controllers
{

    public class UserDetailsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        [Authorize(Roles = "Admin")]
        // GET: UserDetails
        public ActionResult Index()
        {
            return View(db.UserDetails.ToList());
        }
        [Authorize(Roles = "Employee, Manager, Admin")]
        // GET: UserDetails/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();
            var user = db.AspNetUsers.FirstOrDefault(u => u.Id == userId);
            var email = user.Email;
            ViewBag.Email = email;

            return View(userDetail);
        }
        [Authorize(Roles = "Employee")]
        // GET: UserDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Employee")]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName,ResumeFileName")] UserDetail userDetail
            , HttpPostedFileBase resumeFile)
        {
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (resumeFile != null)
                {
                    fileName = Guid.NewGuid() + ".pdf";

                    string path = Server.MapPath("~/Content/Resumes/");
                    resumeFile.SaveAs(path + fileName);
                    userDetail.ResumeFileName = fileName;
                }

            }

            db.UserDetails.Add(userDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        // GET: UserDetails/Edit/5
        [Authorize(Roles = "Employee")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // POST: UserDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Employee")]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,ResumeFileName")] UserDetail userDetail,
            HttpPostedFileBase resumeFile)
        {
            if (ModelState.IsValid)
            {
                if (resumeFile != null)
                {
                    string path = Server.MapPath("~/Content/Resumes/");

                    if (userDetail.ResumeFileName != null)
                    {
                        FileInfo file = new FileInfo(path + userDetail.ResumeFileName);
                        file.Delete();
                    }
                    string fileName = Guid.NewGuid() + ".pdf";

                    resumeFile.SaveAs(path + fileName);
                    userDetail.ResumeFileName = fileName;


                }

                db.Entry(userDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userDetail);
        }

        // GET: UserDetails/Delete/5
        [Authorize(Roles = "Employee")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // POST: UserDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Employee")]
        public ActionResult DeleteConfirmed(string id)
        {
            UserDetail userDetail = db.UserDetails.Find(id);
            db.UserDetails.Remove(userDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Young Investments Careers - @ViewBag.Title</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/Content/assets/img/favicon-32x32.png" rel="icon">
    <link href="~/Content/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">



    <!-- =======================================================
    * Template Name: Company - v2.0.1
    * Template URL: https://bootstrapmade.com/company-free-html-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->


    @Styles.Render("~/Content/css")
    <style>
        footer {
            background: #42A5F5;
            color: white;
            line-height: 50px;
            padding: 0 20px;
        }

        main {
            margin-bottom: 200px;
            padding-bottom: 140px;
            padding-top: 60px;
        }

        body {
            padding-bottom: 0;
        }

        nav ul li a.active {
            color: forestgreen;
        }
    </style>

    <script src="https://code.jquery.com/jquery-1.10.0.min.js"
            integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
            crossorigin="anonymous">

    </script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

    @RenderSection("htmlHead", required: false)
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">
            <a href="@Url.Action("Index","Home")">
                <img src="~/_Archive/Logo/eeae266a-fa97-4bd0-b6dc-0964b6380dc7_200x200.png" style="max-height:40px;" />

            </a>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo mr-auto"><img src="~/Content/assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="nav-menu" class="nav-menu d-none d-lg-block navbar-expand-lg">
                <ul>

                    <li><a href="@Url.Action("Index","Home")"> Home</a></li>


                    @if (User.IsInRole("Manager") || User.IsInRole("Employee"))
                    {
                        <li>@Html.ActionLink("Open Positions", "OpenPositionFilter", "Filters")</li>

                    }

                    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                    {

                        <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
                        <li>@Html.ActionLink("Applications", "Index", "Applications")</li>


                    }



                    @if (User.IsInRole("Admin"))
                    {
                        <li class="drop-down">
                            @Html.ActionLink("Positions", "Index", "Positions")
                            <ul>
                                <li>@Html.ActionLink("Open Positions", "OpenPositionFilter", "Filters")</li>
                            </ul>

                        </li>

                        <li>@Html.ActionLink("Application Status", "Index", "ApplicationStatus")</li>
                        <li class="drop-down">
                            @Html.ActionLink("Users", "Index", "UsersAdmin")

                            <ul>

                                <li>@Html.ActionLink("YI Staff", "Index", "UserDetails")</li>


                                <li> @Html.ActionLink("Users Admin", "Index", "UsersAdmin")</li>
                            </ul>
                        </li>
                    }

                        
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.Partial("_LoginPartial")</li>

                </ul>


            </nav><!-- .nav-menu -->



        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->


    <main id="main">

        <br />
        <br />
        <div class="container border rounded">
            @RenderBody()

        </div>

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer">


        <div class="container d-md-flex py-4">

            <div class="mr-md-auto text-center text-md-left">
                <div class="copyright">
                    &copy; Copyright @DateTime.Now.Year  <strong><span>Young Investments</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/company-free-html-bootstrap-template/ -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>

        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

    <!-- Vendor JS Files -->
    @*<script src="~/Content/assets/vendor/jquery/jquery.min.js"></script>
        <script src="~/Content/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/Content/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
        <script src="~/Content/assets/vendor/php-email-form/validate.js"></script>
        <script src="~/Content/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
        <script src="~/Content/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="~/Content/assets/vendor/venobox/venobox.min.js"></script>
        <script src="~/Content/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
        <script src="~/Content/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
        <script src="~/Content/assets/vendor/aos/aos.js"></script>*@

    <!-- Template Main JS File -->
    @*<script src="~/Content/assets/js/main.js"></script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!--ADDEDjQuery UI CDN-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- ADDED jQuery Ajax CDN-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
    <script>
        
        //adds a class=row to every form
        $(".form-horizontal").wrap("<div class='row' style='padding-left: 10px'></div > ");

        //gives paddingLeft to form group child elements
        let formGroup = document.querySelectorAll(".form-group div");

        for (let i = 0; i < formGroup.length; i++) {
            formGroup[i].style.paddingLeft = "50px";

        }

        
        

        $('.nav-menu ul li a').each(function () { 
            var fullAnchor = $(this).attr('href');
            
            
            var aController = fullAnchor.split('/');
            
            
            
            var fullPath = (window.location.pathname + location.search).substr(1);
            
            var pController = fullPath.split('/');
            
           
            if (aController[1] == pController[0]) {
                
                $(this).addClass('active');
            }
           
            if (aController[1] == 'Home' && window.location.pathname != fullAnchor) {
                $(this).removeClass();
            }
            

        });
    </script>


</body>

</html>

JobBoard.UI.MVC/Views/Shared/_OrigLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>