JobBoard.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;
using PagedList;

namespace JobBoard.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: Filters
        public ActionResult OpenPositionFilter()
        {
            
            var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);
            return View(openPositions.ToList());
        }

        



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI.MVC/Controllers/OpenPositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Data.EF;
using Microsoft.AspNet.Identity;

namespace JobBoard.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin, Manager, Employee")]
    public class OpenPositionsController : Controller
    {
        private JobBoardEntities db = new JobBoardEntities();

        // GET: OpenPositions
        
        public ActionResult Index()
        {
            if (User.IsInRole("Employee"))
            {
                var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);
                return View(openPositions.ToList());
            }
            else
            {
                var userId = User.Identity.GetUserId();
                var managerLocation = db.Locations.Where(l => l.ManagerId == userId).FirstOrDefault();
                var manLocID = managerLocation.LocationId;
                var openPositions = db.OpenPositions.Where(o => o.LocationId == manLocID).Include(o => o.Location).Include(o => o.Position);

                return View(openPositions.ToList());
            }

        }

        public ActionResult ColumbiaIndex()
        {
            var openPositions = db.OpenPositions.Where(o => o.LocationId == 1).Include(o => o.Position);
            return View(openPositions.ToList());
        }
        public ActionResult LenexaIndex()
        {
            var openPositions = db.OpenPositions.Where(o => o.LocationId == 2).Include(o => o.Position);
            return View(openPositions.ToList());
        }
        public ActionResult SanDiegoIndex()
        {
            var openPositions = db.OpenPositions.Where(o => o.LocationId == 3).Include(o => o.Position);
            return View(openPositions.ToList());
        }
        public ActionResult LasVegasIndex()
        {
            var openPositions = db.OpenPositions.Where(o => o.LocationId == 4).Include(o => o.Position);
            return View(openPositions.ToList());
        }
        public ActionResult BostonIndex()
        {
            var openPositions = db.OpenPositions.Where(o => o.LocationId == 5).Include(o => o.Position);
            return View(openPositions.ToList());
        }
        public ActionResult DoverIndex()
        {
            var openPositions = db.OpenPositions.Where(o => o.LocationId == 6).Include(o => o.Position);
            return View(openPositions.ToList());
        }


        // GET: OpenPositions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }
        public PartialViewResult PartialDetails(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            var openPosition = db.OpenPositions.Find(id);
            //if (openPosition == null)
            //{
            //    return HttpNotFound();
            //}
            return PartialView(openPosition);
        }

        // GET: OpenPositions/Create
        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            string currentUserID = User.Identity.GetUserId();
            var managerLocations = db.Locations.Where(loc => loc.ManagerId == currentUserID);
            ViewBag.LocationId = new SelectList(managerLocations, "LocationId", "City");


            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title");
            return View();
        }

        // POST: OpenPositions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult Create([Bind(Include = "OpenPositionId,LocationId,PositionId")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.OpenPositions.Add(openPosition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (User.IsInRole("Manager"))
            {
                string currentUserID = User.Identity.GetUserId();
                var managerLocations = db.Locations.Where(loc => loc.ManagerId == currentUserID);
                ViewBag.LocationId = new SelectList(managerLocations, "LocationId", "City", openPosition.LocationId);

            }
            else
            {
                ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "City", openPosition.LocationId);

            }

            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }
        [Authorize(Roles = "Manager, Admin")]
        // GET: OpenPositions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("Manager"))
            {
                string currentUserID = User.Identity.GetUserId();
                var managerLocations = db.Locations.Where(loc => loc.ManagerId == currentUserID);
                ViewBag.LocationId = new SelectList(managerLocations, "LocationId", "City");

                ViewBag.Message = "You can't edit this Position.";
            }


            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "City", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // POST: OpenPositions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager, Admin")]
        public ActionResult Edit([Bind(Include = "OpenPositionId,LocationId,PositionId")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(openPosition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "City", openPosition.LocationId);
            ViewBag.PositionId = new SelectList(db.Positions, "PositionId", "Title", openPosition.PositionId);
            return View(openPosition);
        }

        // GET: OpenPositions/Delete/5
        [Authorize(Roles = "Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // POST: OpenPositions/Delete/5
        [Authorize(Roles = "Manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPosition openPosition = db.OpenPositions.Find(id);
            db.OpenPositions.Remove(openPosition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard.UI.MVC/Views/OpenPositions/BostonIndex.cshtml
@model IEnumerable<JobBoard.Data.EF.OpenPosition>

@{
    ViewBag.Title = "Boston";

}

@if (User.IsInRole("Employee"))
{

<section id="services" class="services section-bg">
    <div class="container-fluid" data-aos="fade-up">

        <div class="section-title">
            <h2>Open Positions in @ViewBag.Title</h2>

        </div>
        <div class="row">

            <div class="btn-group mx-auto" role="group" aria-label="Locations">
                @Html.ActionLink("Columbia", "ColumbiaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Lenexa", "LenexaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("San Diego", "SanDiegoIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("LasVegas", "LasVegasIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Boston", "BostonIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Dover", "DoverIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })

            </div>
        </div>




    </div>
</section>
}
@if (Model.Count() == 0)
{
    <h3 style="color: red;">No Positions avaialable at this time.</h3>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            @if (User.IsInRole("Employee"))
            {
                <th></th>
            }


            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Title)
                </td>
                @if (User.IsInRole("Employee"))
                {
                    <td>
                        <div>
                            @using (Html.BeginForm("singleClickApply", "Applications", new { @openPositionId = item.OpenPositionId, @applicationStatusId = 1 }, FormMethod.Post, new { @class = "text-sm-center" }))
                            {
                                <input type="submit" name="applyButton" class="btn btn-info btn-xs" value="Single Click Apply!" />
                            }

                        </div>
                    </td>
                }

                <td>

                    @if (User.IsInRole("Employee"))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" })
                    }
                    else
                    {


                        @Html.ActionLink("Edit", "Edit", new { id = item.OpenPositionId }, new { @class = "btn btn-dark" }) @:|
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" }) @:|

                        @Html.ActionLink("Delete", "Delete", new { id = item.OpenPositionId }, new { @class = "btn btn-danger" })
                    }
                </td>
            </tr>
        }

    </table>
}

JobBoard.UI.MVC/Views/OpenPositions/ColumbiaIndex.cshtml
@model IEnumerable<JobBoard.Data.EF.OpenPosition>

@{
    ViewBag.Title = "Columbia";

}

@if (User.IsInRole("Employee"))
{

<section id="services" class="services section-bg">
    <div class="container-fluid" data-aos="fade-up">

        <div class="section-title">
            <h2>Open Positions in @ViewBag.Title</h2>

        </div>
        <div class="row">

            <div class="btn-group mx-auto" role="group" aria-label="Locations">
                @Html.ActionLink("Columbia", "ColumbiaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Lenexa", "LenexaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("San Diego", "SanDiegoIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("LasVegas", "LasVegasIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Boston", "BostonIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Dover", "DoverIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })

            </div>
        </div>




    </div>
</section>
}
@if (Model.Count() == 0)
{
    <h3 style="color: red;">No Positions avaialable at this time.</h3>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            @if (User.IsInRole("Employee"))
            {
                <th></th>
            }


            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Title)
                </td>
                @if (User.IsInRole("Employee"))
                {
                    <td>
                        <div>
                            @using (Html.BeginForm("singleClickApply", "Applications", new { @openPositionId = item.OpenPositionId, @applicationStatusId = 1 }, FormMethod.Post, new { @class = "text-sm-center" }))
                            {
                                <input type="submit" name="applyButton" class="btn btn-info btn-xs" value="Single Click Apply!" />
                            }

                        </div>
                    </td>
                }

                <td>

                    @if (User.IsInRole("Employee"))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" })
                    }
                    else
                    {


                        @Html.ActionLink("Edit", "Edit", new { id = item.OpenPositionId }, new { @class = "btn btn-dark" }) @:|
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" }) @:|

                        @Html.ActionLink("Delete", "Delete", new { id = item.OpenPositionId }, new { @class = "btn btn-danger" })
                    }
                </td>
            </tr>
        }

    </table>
}

JobBoard.UI.MVC/Views/OpenPositions/Create.cshtml
@model JobBoard.Data.EF.OpenPosition

@{
    ViewBag.Title = "Create an Open Position";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <br /><br />
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionId, "PositionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>

        <a href="@Url.Action("OpenPositionFilter","Filters")" class = "btn btn-primary mb-5" > Back to List</a>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobBoard.UI.MVC/Views/OpenPositions/Delete.cshtml
@model JobBoard.Data.EF.OpenPosition

@{
    ViewBag.Title = "Delete Available Position: " +Model.Position.Title;
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<br />
<br />
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "OpenPositionFilter", "Filters", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

JobBoard.UI.MVC/Views/OpenPositions/DoverIndex.cshtml
@model IEnumerable<JobBoard.Data.EF.OpenPosition>

@{
    ViewBag.Title = "Dover";

}

@if (User.IsInRole("Employee"))
{

    <section id="services" class="services section-bg">
        <div class="container-fluid" data-aos="fade-up">

            <div class="section-title">
                <h2>Open Positions Across The Country</h2>

            </div>
            <div class="row">

                <div class="btn-group mx-auto" role="group" aria-label="Locations">
                    @Html.ActionLink("Columbia", "ColumbiaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("Lenexa", "LenexaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("San Diego", "SanDiegoIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("LasVegas", "LasVegasIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("Boston", "BostonIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("Dover", "DoverIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })

                </div>
            </div>

            
            

        </div>
    </section>
}
@if (Model.Count() == 0)
{
    <h3 style="color: red;">No Positions avaialable at this time.</h3>
}
else
{


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            @if (User.IsInRole("Employee"))
            {
                <th></th>
            }


            <th></th>
        </tr>

        @foreach (var item in Model)
        {


            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Title)
                </td>
                @if (User.IsInRole("Employee"))
                {
                    <td>
                        <div>
                            @using (Html.BeginForm("singleClickApply", "Applications", new { @openPositionId = item.OpenPositionId, @applicationStatusId = 1 }, FormMethod.Post, new { @class = "text-sm-center" }))
                            {
                                <input type="submit" name="applyButton" class="btn btn-info btn-xs" value="Single Click Apply!" />
                            }

                        </div>
                    </td>
                }

                <td>

                    @if (User.IsInRole("Employee"))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" })
                    }
                    else
                    {


                        @Html.ActionLink("Edit", "Edit", new { id = item.OpenPositionId }, new { @class = "btn btn-dark" }) @:|
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" }) @:|

                        @Html.ActionLink("Delete", "Delete", new { id = item.OpenPositionId }, new { @class = "btn btn-danger" })
                    }
                </td>
            </tr>
        }



    </table>
}

JobBoard.UI.MVC/Views/OpenPositions/Edit.cshtml
@model JobBoard.Data.EF.OpenPosition

@{
    ViewBag.Title = "Edit Available Poisition: " + Model.Position.Title;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    <br />

    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OpenPositionId)

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PositionId, "Position", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "OpenPositionFilter","Filters", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobBoard.UI.MVC/Views/OpenPositions/LasVegasIndex.cshtml
@model IEnumerable<JobBoard.Data.EF.OpenPosition>

@{
    ViewBag.Title = "Las Vegas";

}

@if (User.IsInRole("Employee"))
{

    <section id="services" class="services section-bg">
        <div class="container-fluid" data-aos="fade-up">

            <div class="section-title">
                <h2>Open Positions in @ViewBag.Title</h2>

            </div>
            <div class="row">

                <div class="btn-group mx-auto" role="group" aria-label="Locations">
                    @Html.ActionLink("Columbia", "ColumbiaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("Lenexa", "LenexaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("San Diego", "SanDiegoIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("LasVegas", "LasVegasIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("Boston", "BostonIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                    @Html.ActionLink("Dover", "DoverIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })

                </div>
            </div>

            
            

        </div>
    </section>
}
@if (Model.Count() == 0)
{
    <h3 style="color: red;">No Positions avaialable at this time.</h3>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            @if (User.IsInRole("Employee"))
            {
                <th></th>
            }


            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Title)
                </td>
                @if (User.IsInRole("Employee"))
                {
                    <td>
                        <div>
                            @using (Html.BeginForm("singleClickApply", "Applications", new { @openPositionId = item.OpenPositionId, @applicationStatusId = 1 }, FormMethod.Post, new { @class = "text-sm-center" }))
                            {
                                <input type="submit" name="applyButton" class="btn btn-info btn-xs" value="Single Click Apply!" />
                            }

                        </div>
                    </td>
                }

                <td>

                    @if (User.IsInRole("Employee"))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" })
                    }
                    else
                    {


                        @Html.ActionLink("Edit", "Edit", new { id = item.OpenPositionId }, new { @class = "btn btn-dark" }) @:|
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" }) @:|

                        @Html.ActionLink("Delete", "Delete", new { id = item.OpenPositionId }, new { @class = "btn btn-danger" })
                    }
                </td>
            </tr>
        }

    </table>
}

JobBoard.UI.MVC/Views/OpenPositions/LenexaIndex.cshtml
@model IEnumerable<JobBoard.Data.EF.OpenPosition>

@{
    ViewBag.Title = "Lenexa";

}

@if (User.IsInRole("Employee"))
{

<section id="services" class="services section-bg">
    <div class="container-fluid" data-aos="fade-up">

        <div class="section-title">
            <h2>Open Positions in @ViewBag.Title</h2>

        </div>
        <div class="row">

            <div class="btn-group mx-auto" role="group" aria-label="Locations">
                @Html.ActionLink("Columbia", "ColumbiaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Lenexa", "LenexaIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("San Diego", "SanDiegoIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("LasVegas", "LasVegasIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Boston", "BostonIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })
                @Html.ActionLink("Dover", "DoverIndex", "OpenPositions", null, new { @class = "btn btn-secondary" })

            </div>
        </div>




    </div>
</section>
}
@if (Model.Count() == 0)
{
    <h3 style="color: red;">No Positions avaialable at this time.</h3>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            @if (User.IsInRole("Employee"))
            {
                <th></th>
            }


            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Title)
                </td>
                @if (User.IsInRole("Employee"))
                {
                    <td>
                        <div>
                            @using (Html.BeginForm("singleClickApply", "Applications", new { @openPositionId = item.OpenPositionId, @applicationStatusId = 1 }, FormMethod.Post, new { @class = "text-sm-center" }))
                            {
                                <input type="submit" name="applyButton" class="btn btn-info btn-xs" value="Single Click Apply!" />
                            }

                        </div>
                    </td>
                }

                <td>

                    @if (User.IsInRole("Employee"))
                    {
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" })
                    }
                    else
                    {


                        @Html.ActionLink("Edit", "Edit", new { id = item.OpenPositionId }, new { @class = "btn btn-dark" }) @:|
                        @Html.ActionLink("Details", "Details", new { id = item.OpenPositionId }, new { @class = "btn btn-primary" }) @:|

                        @Html.ActionLink("Delete", "Delete", new { id = item.OpenPositionId }, new { @class = "btn btn-danger" })
                    }
                </td>
            </tr>
        }

    </table>
}